version: '3'

services:
  frontend:
    build:
      context: .
      dockerfile: docker/DockerfileFrontend
    command: npm start
    stdin_open: true
    tty: true
    environment:
      - NODE_ENV=development
    volumes:
      - ./frontend:/src
      - /src/node_modules
    ports:
      - "3000:3000"
    links:
      - backend
    # depends_on:
    #   - backend

  backend:
    build:
      context: .
      dockerfile: docker/DockerfileBackend
    command: npm run dev
    environment:
     - NODE_ENV=development
     - MONGO_USERNAME=graphql
     - MONGO_PASSWORD=yoga123
     - MONGO_DATABASE=graphqlYoga
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/src
      - ./data/log:/var/log:rw
      - /src/node_modules
    links:
      - mongo
    depends_on:
      - mongo

  nginx:
    image: nginx:1.12.2-alpine
    ports:
      - "80:80"
      - "443:443"
    environment:
      - FRONTEND_PORT=3000  # development
    volumes:
      - ./config/nginx/backend.conf:/etc/nginx/conf.d/default.conf
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./config/nginx/.htpasswd:/etc/nginx/.htpasswd
      - ./config/nginx/ssl:/etc/ssl
      - ./data/log:/var/log/nginx/:rw
      - ./data/media:/var/www/media/:rw
    links:
      - frontend
      - backend
    depends_on:
      - frontend
      - backend

  mongo:
    image: "bitnami/mongodb:latest"
    ports:
      - '27017:27017'
    environment:
      MONGODB_USERNAME: graphql
      MONGODB_PASSWORD: yoga123
      MONGODB_DATABASE: graphqlYoga
    volumes:
      - './data/mongo:/data/db'